Repository mlpack/models, pull requests merged in 2020-05, with the labels that each got.

#7 Initial ci config to set up the azure pipeline.
  .ci/ci.yaml
Labels: c: build system, t: added feature

#10 Remove travis configuration
  .travis.yml
Labels: c: build system, t: bugfix

#11 Fix Style Build
  .travis/config.hpp
  Kaggle/DigitRecognizer/src/DigitRecognizer.cpp
  Kaggle/DigitRecognizerBatchNorm/src/DigitRecognizerBatchNorm.cpp
  Kaggle/DigitRecognizerCNN/src/DigitRecognizerCNN.cpp
  Kaggle/kaggle_utils.hpp
  LSTM/TimeSeries-Multivariate/src/LSTMTimeSeriesMultivariate.cpp
  LSTM/TimeSeries-Univariate/src/LSTMTimeSeriesUnivariate.cpp
  vae/vae_cnn_mnist/src/vae_cnn.cpp
  vae/vae_generate.cpp
Labels: c: build system, c: documentation
