Repository mlpack/models, pull requests merged in 2020-06, with the labels that each got.

#12 Restructuring 2 - Add Utility functions and Run all Tests
  .ci/linux-steps.yaml
  .ci/macos-steps.yaml
  .ci/windows-steps.yaml
  .gitignore
  dataloader/dataloader.hpp
  dataloader/dataloader_impl.hpp
  dataloader/datasets.hpp
  tests/dataloader_tests.cpp
  tests/utils_tests.cpp
  utils/utils.hpp
Labels: t: added feature

#9 Adding documentation for dataloader.
  CONTRIBUTING.md
  README.md
Labels: c: documentation, t: added feature

#15 Fix Typos in LSTMTimeSeriesMultivariate
  LSTM/TimeSeries-Multivariate/src/LSTMTimeSeriesMultivariate.cpp
Labels: c: documentation, t: bugfix

#17 Linux Build Fix.
  .ci/linux-steps.yaml
Labels: c: build system

#18 Image Dataloader with Field type
  .gitignore
  CMakeLists.txt
  augmentation/CMakeLists.txt
  augmentation/augmentation.hpp
  augmentation/augmentation_impl.hpp
  dataloader/dataloader.hpp
  dataloader/dataloader_impl.hpp
  dataloader/datasets.hpp
  dataloader/preprocessor.hpp
  tests/CMakeLists.txt
  tests/augmentation_tests.cpp
  tests/dataloader_tests.cpp
  tests/utils_tests.cpp
  utils/utils.hpp
Labels: t: added feature

#19 Image Dataloader Documentation
  README.md
Labels: c: documentation
